# Site settings
title: From Criminology to Dev
description: Just a portfolio with my resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caroline Chuong
user_description: Weird unicorn cat
user_title: Web Developer
email: caroline.chuong1@gmail.com
twitter_username: Pandora_angora
github_username:  Pandoraaa
gplus_username:  Caroline Chuong

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
